const SUPABASE_URL = "https://evmwczdmvlxudcxhxcvd.supabase.co"
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2bXdjemRtdmx4dWRjeGh4Y3ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYwNzM3MDMsImV4cCI6MjEwMTY0OTcwM30.GqYEhW_wrSzxJPac5dQpbI3qFdLzlsL0XctOYhbJqlg"
const supabaseClient = supabase.createClient(SUPABASE_URL , SUPABASE_ANON_KEY)

